#!/bin/sh
echo "/sys/class/backlight/intel_backlight/max_brightness == "`cat /sys/class/backlight/intel_backlight/max_brightness`


echo "echo $1 > /sys/class/backlight/intel_backlight/brightness"
echo $1 > /sys/class/backlight/intel_backlight/brightness
