#!/bin/sh

which tput >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
tput()
{
    echo -e ""
}
fi;

color_bold=`tput bold`
color_reset=`tput sgr0`

color_underline=`tput smul`
color_no_underline=`tput rmul`
color_blink=`tput blink`
color_rev=`tput rev`

color_black_f=`tput setaf 0`
color_red_f=`tput setaf 1`
color_green_f=`tput setaf 2`
color_yellow_f=`tput setaf 3`
color_blue_f=`tput setaf 4`
color_magenta_f=`tput setaf 5`
color_cyan_f=`tput setaf 6`
color_white_f=`tput setaf 7`

color_black_fl=`tput setaf 8`
color_red_fl=`tput setaf 9`
color_green_fl=`tput setaf 10`
color_yellow_fl=`tput setaf 11`
color_blue_fl=`tput setaf 12`
color_magenta_fl=`tput setaf 13`
color_cyan_fl=`tput setaf 14`
color_white_fl=`tput setaf 15`

color_black_b=`tput setab 0`
color_red_b=`tput setab 1`
color_green_b=`tput setab 2`
color_yellow_b=`tput setab 3`
color_blue_b=`tput setab 4`
color_magenta_b=`tput setab 5`
color_cyan_b=`tput setab 6`
color_white_b=`tput setab 7`

color_black_bl=`tput setab 8`
color_red_bl=`tput setab 9`
color_green_bl=`tput setab 10`
color_yellow_bl=`tput setab 11`
color_blue_bl=`tput setab 12`
color_magenta_bl=`tput setab 13`
color_cyan_bl=`tput setab 14`
color_white_bl=`tput setab 15`

unset tput
