#!/bin/sh

#USERNAME=`cat ~/s/.dynhost_username`
#PASSWORD=`cat ~/s/.dynhost_password`
#HOSTNAME=`cat ~/s/.dynhost_hostname`
IP_FILE_PREFIX=`echo ~/`

NEWIP=''

function check_ip()
{
  echo $1
  NEWIP=`wget -O - --timeout=10 --tries=1 $1 2>/dev/null`
  echo "[$NEWIP]"
  return $?
}

#check_ip "ip.hackertech.pl"
check_ip "https://api.my-ip.io/ip"
check_ip "https://ipapi.co/ip/"
check_ip "api.seeip.org"
check_ip "http://api.ipaddress.com/myip"



exit 0
##########i#############

#if test $? != 0; then
  check_ip "http://myip.dnsomatic.com"
#fi;

#if test $? != 0; then
  check_ip "http://ip1.dynupdate.no-ip.com"
#fi;

#if test $? != 0; then
  check_ip "http://api.ipify.org"
#fi;

#if test $? != 0; then
  check_ip "http://whatismyip.akamai.com"
#fi;

#if test $? != 0; then
  echo "dig +short myip.opendns.com @resolver4.opendns.com"
  NEWIP=`dig +short myip.opendns.com @resolver4.opendns.com`
  echo "[$NEWIP]"
#fi;

#NEWIP=`cat ${IP_FILE_PREFIX}new.ip`
#OLDIP=''

#if test -f ${IP_FILE_PREFIX}old.ip; then
#    OLDIP=`cat ${IP_FILE_PREFIX}old.ip`
#fi;

#echo "NEWIP="$NEWIP" OLDIP="$OLDIP

#if [ "$OLDIP" != "$NEWIP" ]; then
#    TO="https://www.ovh.com/nic/update?system=dyndns&hostname=$HOSTNAME&myip=$NEWIP"
#    wget --user="$USERNAME" --password="$PASSWORD" -O /tmp/dyn.log "$TO" &>/dev/null
#    echo $NEWIP > ${IP_FILE_PREFIX}old.ip
#    echo $NEWIP >> ${IP_FILE_PREFIX}old.ips
#fi
