#!/bin/sh

#USERNAME=`cat ~/s/.dynhost_username`
#PASSWORD=`cat ~/s/.dynhost_password`
#HOSTNAME=`cat ~/s/.dynhost_hostname`
IP_FILE_PREFIX=`echo ~/`

NEWIP=''

RET=1

function check_ip()
{
  if [ "$2" == "wget" ]; then
    echo "wget -O - --timeout=10 $1 2>/dev/null"
    NEWIP=`wget -O - --timeout=10 $1 2>/dev/null`
  else
    echo "dig +short $1"
    NEWIP=`dig +short $1`
  fi;
  RET=$?
  echo "[$NEWIP]"
}

#if test $RET != 0; then
#  check_ip "myip.opendns.com @resolver4.opendns.com" "dig"
#fi;

if test $RET != 0; then
  check_ip "https://ipapi.co/ip/" "wget"
fi;

if test $RET != 0; then
  check_ip "api.seeip.org" "wget"
fi;

if test $RET != 0; then
  check_ip "http://api.ipaddress.com/myip" "wget"
fi;

if test $RET != 0; then
  check_ip "http://myip.dnsomatic.com" "wget"
fi;

if test $RET != 0; then
  check_ip "http://ip1.dynupdate.no-ip.com" "wget"
fi;

if test $RET != 0; then
  check_ip "http://api.ipify.org" "wget"
fi;

if test $RET != 0; then
  check_ip "http://whatismyip.akamai.com" "wget"
fi;

if test $RET != 0; then
  check_ip "https://api.my-ip.io/ip" "wget"
fi;

OLDIP=''
if test -f ${IP_FILE_PREFIX}old.ip; then
    OLDIP=`cat ${IP_FILE_PREFIX}old.ip`
fi;

echo "NEWIP="$NEWIP" OLDIP="$OLDIP

if [ "$OLDIP" != "$NEWIP" ]; then
#    TO="https://www.ovh.com/nic/update?system=dyndns&hostname=$HOSTNAME&myip=$NEWIP"
#    wget --user="$USERNAME" --password="$PASSWORD" -O /tmp/dyn.log "$TO" &>/dev/null
    echo $NEWIP > ${IP_FILE_PREFIX}old.ip
    echo "$NEWIP - `date`" >> ${IP_FILE_PREFIX}old.ips
fi

