#!/bin/sh

if [ -z "$1" ]; then
    echo "$0 <ramdisk_name>"
    exit 1
fi;

if [ -f ~/.air ]; then
    echo "*** air ***"
    ramdisk_name=$1   
    hdiutil detach /Volumes/$ramdisk_name

else
    echo "???"
fi;


