#!/bin/sh

if [ -z "$1" ]; then
    echo "$0 <name>"
    exit 1;
fi;

if [ -f "$1.sh" ]; then
    echo "$1.sh exists."
#    echo "#!/bin/sh" >> "$1.sh"
else
    echo "#!/bin/sh" > "$1.sh"
    chmod +x "$1.sh"
fi;


