#!/bin/sh

if [ -z $2 ]; then
    echo "$0 <name> {0, 1, 2, 3, z, s, fast}"
    exit 1;
fi;

echo "clang --target=wasm32-wasi -O$2 -nostdlib -Wl,--export-all -Wl,--no-entry -o $1.wasm $1.c"
clang --target=wasm32-wasi -O$2 -nostdlib -Wl,--export-all -Wl,--no-entry -o $1.wasm $1.c
